### ISSUE TITLE
Add input types for creation

### ISSUE THREAD

**Issue by Sytten** [microsoftgraph/msgraph-typescript-typings#183]
Sometimes the API accepts different parameters as input than what it returns.
One such example is the create event API: https://docs.microsoft.com/en-us/graph/api/calendar-post-events?view=graph-rest-1.0&tabs=http
If you want to add a conference you specify:
```
event.isOnlineMeeting = true
event.onlineMeetingProvider = "someprovider"
```
But currently the type that we can use is `Event` which doesn't contain that parameter.

**Comment by MIchaelMainer** [comment]
Which version of the typings are you using? They do exist in the typings file:

https://github.com/microsoftgraph/msgraph-typescript-typings/blob/master/microsoft-graph.d.ts#L1872

I suggest that you refresh your typings to the latest version.

**Comment by Sytten** [comment]
Agreed this was a missing update, but maybe I should rephrase that as: mark field as readonly when they cant be set in input?

**Comment by MIchaelMainer** [comment]
@Sytten I wish I had a way to determine which fields are read-only. Specifically, we'd need to have some context since fields can be read-only in some context, but read-write in other. At best, we could get this expressed through [InsertRestrictions](https://github.com/oasis-tcs/odata-vocabularies/blob/master/vocabularies/Org.OData.Capabilities.V1.md#insertrestrictionstype) for the properties where we no for sure they are only set by the service.

**Comment by Sytten** [comment]
Some of it could be parsed from the description but I agree that is not ideal. I just feel the typing is not that nice to use for input right now, output is great though.
